### ISSUE TITLE
Impossible de redémarrer freebox

### ISSUE THREAD

**Issue by fenice2** [ugomeda/freebox-os-reboot#1]
Merci pour ce grand script, je l’utilise depuis quelques mois et il a bien fonctionné, jusqu’à aujourd’hui.

Évidemment, j’ai eu des problèmes causés par ce bug https://dev.freebox.fr/bugs/task/22818 - malheureusement, lorsque mon service IPv4 est tombé aujourd’hui, j’ai supposé que mon exécution prévue de votre script a couru, mais il n’a pas redémarrer la Freebox.

Lorsque j’ai testé le script manuellement, il a produit cette erreur:

./freebox-os-reboot.py reboot
Lancement du redémarrage de la Freebox...
 ERREUR
HTTPSConnectionPool(host='212.27.38.253', port=58372): Max retries exceeded with url: /api/v8/login/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7c70b900b8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

La seule chose qui a changé récemment sont les mises à jour du logiciel Freebox et il est actuellement à la libération 4.2.2 et les détails de l’API sont les suivants:

box_model_name	"Freebox Server Mini (r2)"
api_base_url	"/api/"
https_port	58372
device_name	"Freebox Server"
https_available	true
box_model	"fbxgw-r2/mini"
api_domain	"3w6bkreb.fbxos.fr"
uid	"2cec3b3c48fe89038017f4fd0907d362"
api_version	"8.0"
device_type	"FreeboxServer1,2"

Il s’agit d’une Freebox mini 4K et évidemment, j’ai créé le APP_TOKEN et modifié le paramètre de l’application sur la Freebox que ce script a fonctionné OK. Y a-t-il quelque chose que je puisse faire pour résoudre ce problème ?

Avez-vous besoin de plus d’informations?

**Comment by ugomeda** [comment]
Pas besoin de plus d'informations, j'arrive à reproduire sans soucis.

Le port HTTPs déclaré par l'API n'a pas l'air d'être ouvert depuis la mise à jour...

J'ajoute une option pour ça.

**Comment by ugomeda** [comment]
J'ai poussé une mise à jour, est-ce que ça corrige bien le problème ?

**Comment by fenice2** [comment]
Merci pour la solution rapide, je ne suis pas à la maison aujourd’hui et je vais tester ce demain.

**Comment by fenice2** [comment]
Parfait, le problème est résolu. Merci encore pour la solution rapide.
